[package]
name = "dashboard-app"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[dependencies]
maud.workspace = true

reqwest.workspace = true
moka.workspace = true
futures.workspace = true
tokio.workspace = true

serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
ulid.workspace = true
color-eyre.workspace = true
tracing.workspace = true

[build-dependencies]
# Format the compile timestamp embedded in the footer.
chrono.workspace = true
